name: beeline2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - r=4.3
  - rpy2==3.5.11
  - matplotlib==3.10
  - pandas==2.3
  - networkx==3.4.2
  - seaborn==0.13.2
  - tqdm==4.67.1
  - numpy==2.2.6
  - scikit-learn==1.7
  - PyYAML
  - pytables
  - openpyxl
  - bioconda::mygene==3.2.2

  # for building documentation only
  - conda-forge::sphinx
  - conda-forge::sphinx_rtd_theme
